# Generated by Django 4.1.4 on 2022-12-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ims', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='item',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
